print("==============================================")
print("BEST FRIEND MAKER")
print("==============================================")
print("Hi. I'm the computer")
input("What's your name?")
print("Hi, Mr.Baldus! what's your favorite color?")
input("kelly green")
print("No way! My favorite color is also kelly green")
print("what's your favorite movie?")
input("The Princess Bride")
print("What!?! My favorite movie is also The Princess Bride!")
print("what is your favorite game?")
input("soccer")
print("Get out of here! My favorite game is soccer, too!")
print("we like the same things! We should be best friends!")